# Docker compose file to spin up the services needed to support bio auth
#
version: '3.5'

networks:
  agency-network:
    name: agency-network
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24

services:
  protocol-identity-service:
    build:
      context: .
      dockerfile: Dockerfile.identityservice
    image: protocol-identity-service
    container_name: protocol-identity-service
    ports:
      - "8081:8080"
    env_file:
      - identity_service/.env
    networks:
      - agency-network
    depends_on:
      - identity-template-db
      - identity-intelligence-db
    tty: true

  bio-auth-service:
    build:
      context: .
      dockerfile: Dockerfile.bioauthservice
    image: bio-auth-service
    container_name: bio-auth-service
    ports:
      - "8082:8080"
    networks:
      - agency-network
    depends_on:
      - identity-template-db
    tty: true

  identity-template-db:
    command: postgres -c logging_collector=on -c log_destination=stderr -c listen_addresses='*'
    image: postgres:11
    container_name: identity-template-db
    restart: always
    env_file:
      - identity_template_db/.env
    volumes:
      - ./logs/postgres:/logs:z
    networks:
      - agency-network
    tty: true

  identity-intelligence-db:
    command: postgres -c logging_collector=on -c log_destination=stderr -c listen_addresses='*'
    image: postgres:11
    container_name: identity-intelligence-db
    restart: always
    env_file:
      - identity_intelligence_db/.env
    volumes:
      - ./logs/postgres:/logs:z
    networks:
      - agency-network
    tty: true

  bioanalyzer-service:
    build:
      context: .
      dockerfile: Dockerfile.bioanalyzerservice
    image: bioanalyzer-service
    container_name: bioanalyzer-service
    working_dir: /app
    env_file:
      - bioanalyzer_service/.env
    ports:
      - "8089:8080"
    networks:
      - agency-network
    depends_on:
      - protocol-identity-service
      - bio-auth-service
    tty: true
