version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - openjdk-install/openjdk:
          version: 11
      - run:
          name: Prepare Environment
          command: ./scripts/useDummyEnvFiles.sh --force
      - run:
          name: build and test bioanalyzer service
          command: |
            cd bioanalyzer_service
            ./gradlew clean
            ./gradlew build
      - run:
          name: build and test bio auth service
          command: |
            cd bio_auth_service
            ./gradlew clean
            ./gradlew build
      - run:
          name: Spin up bio-auth services to confirm they can actually execute
          command: |
            docker network prune -f
            docker-compose up -d
      - run:
          name: wait for bio-auth services to come up
          command: ./scripts/healthstack.sh
      - run:
          name: Spin down bio-auth services
          command: |
            docker stop $(docker ps -aq)
            docker-compose down

workflows:
  build-test-deploy:
    jobs:
      - build-and-test:
          filters: # run for all branches AND tags
            tags:
              only: /.*/
      - docker/publish:
          requires:
            - build-and-test
          filters: # only run for semver tagged versions
            tags:
              only: /^([0-9]+)\.([0-9]+)\.([0-9]+)/
            branches:
              ignore: /.*/
          after_checkout:
            - openjdk-install/openjdk:
                version: 11
            - run:
                name: build bioanalyzer service
                command: |
                  cd bioanalyzer_service
                  ./gradlew clean
                  ./gradlew build
          update-description: true
          dockerfile: ./Dockerfile.bioanalyzerservice
          image: kivaprotocol/bioanalyzer
          tag: << pipeline.git.tag >>
      - docker/publish:
          requires:
            - build-and-test
          filters: # only run for semver tagged versions
            tags:
              only: /^([0-9]+)\.([0-9]+)\.([0-9]+)/
            branches:
              ignore: /.*/
          after_checkout:
            - openjdk-install/openjdk:
                version: 11
            - run:
                name: build bio auth service
                command: |
                  ./scripts/useDummyEnvFiles.sh --force
                  cd bio_auth_service
                  ./gradlew clean
                  ./gradlew build
          update-description: true
          dockerfile: ./Dockerfile.bioauthservice
          image: kivaprotocol/bioauth
          tag: << pipeline.git.tag >>

orbs:
  docker: circleci/docker@1.3.0
  openjdk-install: cloudesire/openjdk-install@1.2.3
