version: 2.1

jobs:
  build-and-test:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - openjdk-install/openjdk:
          version: 11
      - run:
          name: Prepare Environment
          command: ./scripts/useDummyEnvFiles.sh --force
      - run:
          name: build and test bioanalyzer service
          command: |
            cd bioanalyzer_service
            ./gradlew clean
            ./gradlew build
      - run:
          name: build and test bio auth service
          command: |
            cd bio_auth_service
            ./gradlew clean
            ./gradlew build
      - run:
          name: Spin up bio-auth services to confirm they can actually execute
          command: |
            docker network prune -f
            docker-compose up -d
      - run:
          name: wait for bio-auth services to come up
          command: ./scripts/healthstack.sh
      - run:
          name: Spin down bio-auth services
          command: |
            docker stop $(docker ps -aq)
            docker-compose down

  protocol-integration-tests:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - run:
          name: Pull protocol-integration-tests
          command: git clone https://github.com/kiva/protocol-integration-tests ./
      - run:
          name: Setup environment
          command: |
            ./scripts/setup_env.sh
            echo $AUTH0_ENV | base64 --decode >> .env
            echo ' [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"' >> $BASH_ENV
      - run:
          name: Node npm setup
          command: |
            nvm install v14.15.1
            node -v
            nvm alias default v14.15.1
      - run:
          name: Get ACAPy
          command: docker pull bcgovimages/aries-cloudagent:py36-1.16-1_0.7.1
      - run:
          name: Override for gateway image
          command: ./scripts/setup_override.sh -r guardian-bio-auth -s bio_auth_service,bioanalyzer_service -f docker-compose.yml -e scripts/useDummyEnvFiles.sh
      - run:
          name: Start docker compose and wait for readiness
          command: |
            docker system prune -f
            docker-compose -f docker-compose.yml build --no-cache
            docker-compose -f docker-compose.yml up -d
            sleep 20
            docker-compose -f docker-compose.yml logs
      - run:
          name: Healthcheck services
          command: ./scripts/healthstack.sh
      - run:
          name: Setup integration tests
          command: |
            npm install
            ./scripts/setup_fixtures.sh
      - run:
          name: Running integration tests
          command: |
            if ! npm run test ; then
              echo "Tests failed. Server logs:";
              docker-compose -f docker-compose.yml logs;
              exit 1;
            fi

  push-to-dev:
    machine:
      image: ubuntu-1604:201903-01
    parameters:
      tag:
        default: latest
        description: Tag of bio-auth-service and bioanalyzer-service to push to dev
        type: string
      service:
        description: Name of service to push to dev
        type: string
      helm-charts:
        description: Location of the helm charts to be used in this deployment
        type: string
    steps:
      - checkout
      - kube-orb/install
      - kube-orb/install-kubeconfig:
          kubeconfig: KUBECONFIG_BASE64
      - aws-eks/install-aws-iam-authenticator
      - helm/install-helm-client:
          version: v3.2.4
      - run:
          name: Deploy service to dev cloud
          command: helm upgrade --install <<parameters.service>> <<parameters.helm-charts>> --set image.tag=<<parameters.tag>>

workflows:
  build-test-deploy:
    jobs:
      - build-and-test:
          filters: # run for all branches AND tags
            tags:
              only: /.*/
      - protocol-integration-tests:
          context:
            - integration-test-context
          requires:
            - build-and-test
          filters: # only run for semver tagged versions
            tags:
              only: /^([0-9]+)\.([0-9]+)\.([0-9]+)/
            branches:
              ignore: /.*/
      - docker/publish:
          name: docker/publish-bioanalyzer
          requires:
            - build-and-test
            - protocol-integration-tests
          filters: # only run for semver tagged versions
            tags:
              only: /^([0-9]+)\.([0-9]+)\.([0-9]+)/
            branches:
              ignore: /.*/
          after_checkout:
            - openjdk-install/openjdk:
                version: 11
            - run:
                name: build bioanalyzer service
                command: |
                  cd bioanalyzer_service
                  ./gradlew clean
                  ./gradlew build
          update-description: true
          dockerfile: ./Dockerfile.bioanalyzerservice
          image: kivaprotocol/bioanalyzer
          tag: << pipeline.git.tag >>,latest
      - docker/publish:
          name: docker/publish-bio-auth
          requires:
            - build-and-test
            - protocol-integration-tests
          filters: # only run for semver tagged versions
            tags:
              only: /^([0-9]+)\.([0-9]+)\.([0-9]+)/
            branches:
              ignore: /.*/
          after_checkout:
            - openjdk-install/openjdk:
                version: 11
            - run:
                name: build bio auth service
                command: |
                  ./scripts/useDummyEnvFiles.sh --force
                  cd bio_auth_service
                  ./gradlew clean
                  ./gradlew build
          update-description: true
          dockerfile: ./Dockerfile.bioauthservice
          image: kivaprotocol/bioauth
          tag: << pipeline.git.tag >>,latest
      - push-to-dev:
          name: push-to-dev-bio-auth
          context:
            - continuous-deployment-dev
          requires:
            - docker/publish-bio-auth
          filters: # only run for semver tagged versions
            tags:
              only: /^([0-9]+)\.([0-9]+)\.([0-9]+)/
            branches:
              ignore: /.*/
          tag: << pipeline.git.tag >>
          service: protocol-bio-auth
          helm-charts: bio_auth_service/helm-config
      - push-to-dev:
          name: push-to-dev-bioanalyzer
          context:
            - continuous-deployment-dev
          requires:
            - docker/publish-bioanalyzer
          filters: # only run for semver tagged versions
            tags:
              only: /^([0-9]+)\.([0-9]+)\.([0-9]+)/
            branches:
              ignore: /.*/
          tag: << pipeline.git.tag >>
          service: protocol-bioanalyzer
          helm-charts: bioanalyzer_service/helm-config

orbs:
  docker: circleci/docker@1.3.0
  openjdk-install: cloudesire/openjdk-install@1.2.3
  kube-orb: circleci/kubernetes@0.11.1
  aws-eks: circleci/aws-eks@1.0.1
  helm: circleci/helm@1.2.0
