# Builder stage needs JDK and gradle
FROM openjdk:8-jdk-alpine as builder
WORKDIR /app
COPY . .
RUN ./gradlew build

# Runner stage only needs JRE and JAR
FROM openjdk:8-jre-alpine
WORKDIR /app
COPY --from=builder /app/build/libs/*.jar ./app.jar
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom", "-jar","./app.jar", "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000s"]
