version: '3'

networks:
  local-network:
    external: true

services:
  identity-service:
    build: ./
    image: identity-service
    container_name: identity-service
    ports:
      - "8081:8080"
    env_file:
      - .env
    networks:
      - local-network
    tty: true
