# Default values for helm-config.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: kivaprotocol/bioanalyzer
  tag: latest # leave this as latest. CICD will set a specific version tag.
  pullPolicy: Always
  imagePullSecrets:
    - name: "regcred"

nameOverride: "bioanalyzer"
fullnameOverride: "bioanalyzer"
secrets: "bioanalyzer"

strategy:
  type: "RollingUpdate"

service:
  type: ClusterIP
  port: 8089
  containerPort: 8080
  protocol: TCP

resources:
  limits:
    cpu: 1100m
    memory: 2671629701
  requests:
    cpu: 1100m
    memory: 2671629701

#affinity: {}
#
#tolerations:
#  - effect: NoSchedule
#    key: crypto
#    operator: Equal
#    value: "true"
#
#nodeSelector:
#    dedicated: crypto
